Use scoped_search STI support branch
    CommonParametersControllerTest#test_index:
    ActionView::Template::Error: undefined method `id' for nil:NilClass
        app/models/parameters/host_parameter.rb:8:in `to_s'
        app/helpers/application_helper.rb:31:in `link_to'
        app/helpers/application_helper.rb:116:in `link_to_if_authorized'
        app/views/common_parameters/index.html.erb:18:in `block in _app_views_common_parameters_index_html_erb___2409158994488278606_147245200'
        app/views/common_parameters/index.html.erb:16:in `_app_views_common_parameters_index_html_erb___2409158994488278606_147245200'
        app/controllers/concerns/application_shared.rb:14:in `set_timezone'
        app/models/concerns/foreman/thread_session.rb:32:in `clear_thread'
        test/controllers/common_parameters_controller_test.rb:5:in `test_index'

The controller is calling CommonParameter.search_for, but this generates:

    irb(main):002:0> CommonParameter.search_for
    2016-09-23T14:53:05  [sql] [D]   Parameter Load (0.7ms)  SELECT "parameters".* FROM "parameters" ORDER BY parameters.name

However on develop with 4.2:

    2016-09-23T14:52:35  [sql] [D]   CommonParameter Load (0.4ms)  SELECT "parameters".* FROM "parameters" WHERE "parameters"."type" IN ('CommonParameter')  ORDER BY parameters.name

This causes the view to try and render HostParameters from fixtures that have broken associations to a non-existent host.

Fixed in scoped_search, PR 159.

Can be backported to develop.
Required for rails5.